### ISSUE TITLE
Laravel installation misses /src/Integration/Laravel folder

### ISSUE THREAD

**Issue by pbohny** [iivannov/branchio#1]
When manually added from src, Facade is not recognized. Can't be used following the install manual for Laravel

**Comment by od3n** [comment]
i'm using following command to install the package

`composer install iivannov/branchio:dev-master`

but i'm getting this error

`A facade root has not been set.`

sample code

```
use Branchio;

Branchio::createLink($data, 'test');

```

**Comment by plicas** [comment]
Same error as @od3n 

@od3n @iivannov i change the BranchioServiceProvider to:

`  $app = app();
      $config = $app->make('config');
      $key = $config->get('services.branchio.key');
      $secret = $config->get('services.branchio.secret');
      if (!$key || !$secret){
          throw new \InvalidArgumentException('Missing BranchIO key and secret in configuration files');
          new \Iivannov\Branchio\Client($key, $secret);
      }
      $branch = new \Iivannov\Branchio\Client($key, $secret);
      $this->app->bindIf(\Iivannov\Branchio\Client::class, function () use ($branch) {
        return $branch;
      });`

And it's working.

**Comment by iivannov** [comment]
Issue was fixed with latest merge #2 , thanks to @samy . Please update your package to version 1.0.2.
Sorry for the inconvenience!
